### PR TITLE
Data replication logic added for vertica with errors on jar fiels

### PR DESCRIPTION
**Pull request by RathikaMaf**

### CODE REVIEW

**Comment by ufuksak** [comment]
@RathikaMaf , are you able to fix the conflicts? Thank you

**Comment by carlos-verdes** [comment]
Is this branch rebased with our latest updates?

**Comment by RathikaMaf** [comment]
> @RathikaMaf , are you able to fix the conflicts? Thank you

Conflicts has been resolved

**Comment by RathikaMaf** [comment]
> 

Yes this feature branch has the updated working code

**Comment by RathikaMaf** [comment]
Closing this pr as the new pr raised with the logic for syncing table records . @ufuksak as discussed the code is not fully working and need to be updated for the second levels of syncing process.

**Pull request closed without merging**
